name: medpg
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_svg:
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  intl:




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 200

